language: nix

os:
  - linux
  - osx

env:
  - HC=ghc844

before_install:
  - curl https://raw.githubusercontent.com/int-index/nix-cabal/master/nix-cabal -o nix-cabal && chmod u+x nix-cabal
  - travis_retry ./nix-cabal new-update

script:
  - ./nix-cabal new-build all
  - ./nix-cabal new-exec which slay-gtk-example

cache:
  directories:
    - ~/.cabal
    - ~/.ghc
