language: generic

os:
  - linux
  - osx

sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=/opt/ghc/8.2.1/bin:/opt/cabal/2.0/bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install ghc cabal-install gtk+3; fi
  - travis_retry cabal update

script:
  - cabal new-build all
  - test -f dist-newstyle/build/*/*/slay-gtk-*/c/slay-gtk-example/build/slay-gtk-example/slay-gtk-example

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.2.1
    - cabal-install-2.0
    - libgtk-3-dev 
